config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'update_rate', action: :update_rate, controller: 'static_pages'
  get 'check_balance', action: :check_balance, controller: 'wallets'

  resources :wallets, only: %i[index create update destroy]
  resources :settings, only: %i[index create update destroy]
  resources :transactions, only: %i[index new create show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def alert_errors
    errors.full_messages.join(' | ')
  end
end

app/models/setting.rb
class Setting < ApplicationRecord
  encrypts :title, deterministic: true
  encrypts :value

  before_validation :normalize_title

  validates :title, :value, presence: true
  validates :title, uniqueness: true

  private

  def normalize_title
    title.downcase! if title.present?
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  encrypts :recip_email, :recip_btc_address, :txid, deterministic: true

  enum status: { success: 0, fail: 1 }

  validates :amount_send, :amount_get, :recip_email, :recip_btc_address, :ex_fee, :ex_rate, :net_fee, presence: true
  validates :amount_send, numericality: { greater_than_or_equal_to: 0.1, less_than_or_equal_to: 30 }
  validates :recip_email, format: { with: /\A[\w.-]+@[a-z\d]+\.[a-z]+\z/ }
  validates :kyc, acceptance: true
  validate :check_balance
  validate :allowed_btc_amount
  validate :btc_address

  scope :success, -> { where(status: 0) }

  private

  def allowed_btc_amount
    return if amount_get.nil?

    ex_rate = Setting.find_by(title: 'ex_rate')&.value.to_f
    ex_fee = Setting.find_by(title: 'ex_fee')&.value.to_f / 100
    net_fee = Setting.find_by(title: 'net_fee')&.value.to_f
    max_amount_get = ((30 * ex_rate) - ((30 * ex_rate) * ex_fee) - net_fee).round(8)

    errors.add(:amount_get, "cannot be more #{max_amount_get}") if amount_get > max_amount_get
  end

  def btc_address
    Bitcoin.network = :testnet

    return if Bitcoin.valid_address?(recip_btc_address)

    errors.add(:recip_btc_address, 'invalid for testnet network')
  end

  def check_balance
    return if amount_get.nil?

    CheckBalanceService.new.call

    wallet_address = Setting.find_by(title: 'ex_wallet')&.value
    wallet_balance = Wallet.find_by(address: wallet_address)&.balance.to_f

    errors.add(:amount_get, "cannot be more #{wallet_balance}") if amount_get > wallet_balance
  end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  encrypts :key, :priv_key, :pub_key
  encrypts :address, :title, deterministic: true

  enum action: { generate: 'generate', import: 'import' }

  validates :title, :address, :key, :priv_key, :pub_key, presence: true
  validates :title, :address, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: %i[update destroy]
  http_basic_authenticate_with name: Rails.application.credentials.dig(:http_auth, :name),
                               password: Rails.application.credentials.dig(:http_auth, :password)

  def index
    @settings = Setting.all
    @new_setting = Setting.new
  end

  def create
    @setting = Setting.new(setting_params)

    if @setting.save
      redirect_to settings_path, notice: "Setting parametr '#{@setting.title}' was successfully created."
    else
      redirect_to settings_path, alert: @setting.alert_errors
    end
  end

  def update
    if @setting.update(setting_params)
      redirect_to settings_path, notice: "Setting parametr '#{@setting.title}' was successfully updated."
    else
      redirect_to settings_path, alert: @setting.alert_errors
    end
  end

  def destroy
    @setting.destroy
    redirect_to settings_url, notice: 'Setting parametr was successfully destroyed.'
  end

  private

  def set_setting
    @setting = Setting.find(params[:id])
  end

  def setting_params
    params.require(:setting).permit(:title, :value, :description)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index; end

  def update_rate
    ExchangeRateService.new('USDT', 'BTC').call

    render turbo_stream: turbo_stream.replace('ex_rate', partial: 'ex_rate')
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show]
  http_basic_authenticate_with name: Rails.application.credentials.dig(:http_auth, :name),
                               password: Rails.application.credentials.dig(:http_auth, :password),
                               except: %i[new create show]

  def index
    @pagy, @transactions = pagy(Transaction.all.order(created_at: :desc))
    @all_transactions = Transaction.all
  end

  def show; end

  def new
    @transaction = Transaction.new
  end

  def create
    @new_transaction = Transaction.new(transaction_params)

    if @new_transaction.valid?
      broadcast_transaction = CreateTransactionService.new(@new_transaction).call
      @transaction = BroadcastTransactionService.new(broadcast_transaction, @new_transaction).call

      redirect_to transaction_path(@transaction)
    else
      render json: ErrorSerializer.serialize(@new_transaction.errors), status: :unprocessable_entity
    end
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:recip_email, :amount_get, :amount_send, :currency_from,
                                        :currency_to, :recip_btc_address, :kyc, :ex_fee, :ex_rate, :net_fee)
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :set_wallet, only: %i[update destroy]
  http_basic_authenticate_with name: Rails.application.credentials.dig(:http_auth, :name),
                               password: Rails.application.credentials.dig(:http_auth, :password)

  rescue_from StandardError, with: :not_valid_base58_string

  def index
    @wallets = Wallet.all
    @new_wallet = Wallet.new
  end

  def create
    @wallet = GenerateWalletService.new(params).call

    if @wallet.save
      redirect_to wallets_path, notice: "Wallet '#{@wallet.title}' was successfully created."
    else
      redirect_to wallets_path, alert: @wallet.alert_errors
    end
  end

  def update
    if @wallet.update(wallet_params)
      redirect_to wallets_path, notice: "Wallet '#{@wallet.title}' was successfully updated."
    else
      redirect_to wallets_path, alert: @wallet.alert_errors
    end
  end

  def destroy
    @wallet.destroy
    redirect_to wallets_url, notice: 'Wallet was successfully destroyed.'
  end

  def check_balance
    CheckBalanceService.new.call

    redirect_to wallets_path, notice: 'Wallet balances was successfully updated'
  end

  private

  def set_wallet
    @wallet = Wallet.find(params[:id])
  end

  def wallet_params
    params.require(:wallet).permit(:title, :key)
  end

  def not_valid_base58_string
    redirect_to wallets_path, alert: 'Key not a valid Base58 string'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def bootstrap_class(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-success',
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def ex_rate
    Setting.find_by(title: 'ex_rate')&.value || 'Parameter not set'
  end

  def ex_fee
    Setting.find_by(title: 'ex_fee')&.value || 'Parameter not set'
  end

  def net_fee
    Setting.find_by(title: 'net_fee')&.value || 'Parameter not set'
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def total_tx(transactions)
    transactions.count
  end

  def total_ex_fee(transactions)
    transactions.success.sum(&:ex_fee)
  end

  def total_success_tx(transactions)
    transactions.success.count
  end
end

app/views/layouts/_flash.html.erb
<div data-controller="autohide">
  <% flash.each do |key, value| %>
    <div class="alert <%= bootstrap_class(key)%> alert-dismissible fade show" role="alert" style="position:absolute; z-index: 2; right: 10px">
      <%= content_tag :div, value, id: key %>
    <% end %>
    <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <title>CryptoExchange</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <div class="container">
      <%= render "layouts/flash" if flash.any? %>
      <%= render "shared/header" %>
      <%= yield %>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/settings/_settings.html.erb
<div class="table-responsive">
  <table class="table table-bordered table-sm">
    <h3 class="text-center mt-5">Settings</h3>
    <thead class="text-center">
    <tr>
      <th>Title</th>
      <th>Value</th>
      <th>Description</th>
      <th colspan="2">Action</th>
    </tr>
    </thead>

    <tbody>
    <% @settings.each do |setting| %>
      <%= form_with model: setting do |f| %>
        <tr>
          <td class="align-middle"><%= f.text_field :title, class: 'form-control' %></td>
          <% if setting&.title == 'ex_rate' %>
            <td class="align-middle text-center"><%= setting.value %></td>
          <% else %>
            <td class="align-middle"><%= f.text_field :value, class: 'form-control' %></td>
          <% end %>
          <td class="align-middle"><%= f.text_field :description, class: 'form-control' %></td>
          <td class="align-middle text-center">
          <%= button_tag type: 'submit', data: { turbo_confirm: "Are you sure to update setting?" },
                                        class: "btn btn-success btn-sm" , title: "Update" do %>
            <i class="bi bi-arrow-clockwise"></i>
          <% end %>
          </td>
          <td class="align-middle text-center">
          <%= link_to setting, data: { turbo_method: :delete, turbo_confirm: "Are you sure to delete setting?" },
                              class: "btn btn-danger btn-sm", title: "Delete" do %>
            <i class="bi bi-trash"></i>
          <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/settings/index.html.erb
<div class="container py-3">
  <div class="table-responsive">
    <table class="table table-dark table-bordered text-center table-sm">
      <h3 class="text-center">Add setting</h3>
      <tbody>
      <tr>
        <%= form_with model: @new_setting do |f| %>
          <td class="align-middle"><%= f.text_field :title, class: 'form-control', placeholder: 'Title*', autofocus: true %></td>
          <td class="align-middle"><%= f.text_field :value, class: 'form-control', placeholder: 'Value*' %></td>
          <td class="align-middle"><%= f.text_field :description, class: 'form-control', placeholder: 'Description' %></td>
          <td class="align-middle"><%= button_tag type: 'submit', title: "Add", class: "btn btn-primary btn-sm" do %>
              <i class="bi bi-plus-square"></i>
            <% end %>
          </td>
          </tr>
        <% end %>
        </tbody>
    </table>
  </div>
  <%= render "settings", settings: @settings %>
</div>

app/views/shared/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
  <div class="col-md-4 d-flex align-items-center">
    <span class="mb-3 mb-md-0 text-muted">&copy; <%= Time.now.year %> Hodl, Inc</span>
  </div>

  <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
    <li class="ms-3"><i class="bi bi-browser-chrome"></i></li>
    <li class="ms-3"><i class="bi bi-twitter"></i></li>
    <li class="ms-3"><i class="bi bi-linkedin"></i></li>
  </ul>
</footer>

app/views/shared/_header.erb
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
  <%= link_to root_path, class: "d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none" do %>
    <svg class="bi me-2" width="40" height="32"></svg>
    <span class="fs-4">Crypto Exchange</span>
  <% end %>

  <ul class="nav nav-pills">
    <li class="nav-item"><%= link_to "Exchange", new_transaction_path, class: "nav-link" %></li>
    <li class="nav-item"><%= link_to "Transactions", transactions_path, class: "nav-link" %></li>
    <li class="nav-item"><%= link_to "Wallets", wallets_path, class: "nav-link" %></li>
    <li class="nav-item"><%= link_to "Settings", settings_path, class: "nav-link" %></li>
  </ul>
</header>

app/views/shared/_header.html.erb
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
  <%= link_to root_path, class: "d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none" do %>
    <svg class="bi me-2" width="40" height="32"></svg>
    <span class="fs-4">Crypto Exchange</span>
  <% end %>

  <ul class="nav nav-pills">
    <li class="nav-item"><%= link_to "Exchange", new_transaction_path, class: "nav-link" %></li>
    <li class="nav-item"><%= link_to "Transactions", transactions_path, class: "nav-link" %></li>
    <li class="nav-item"><%= link_to "Wallets", wallets_path, class: "nav-link" %></li>
    <li class="nav-item"><%= link_to "Settings", settings_path, class: "nav-link" %></li>
  </ul>
</header>

app/views/static_pages/_ex_rate.html.erb
<%= turbo_frame_tag 'ex_rate' do %>
  Current exchange rate (BTC) - <%= ex_rate %>
<% end %>

app/views/static_pages/index.html.erb
<div class="row row-cols-1 row-cols-md-2 mb-3 text-center">
  <div class="col">
    <div class="card mb-4 rounded-3 shadow-sm">
      <div class="card-header py-3">
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">USDT to BTC</h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>Exchange fee (%) - <%= ex_fee %></li>
          <li>Network fee (BTC) - <%= net_fee %><li>
          <li><%= render 'ex_rate' %></li>
        </ul>
        <div class="row">
          <div class="col-md-6">
            <%= link_to "Exchange", new_transaction_path, class: 'w-100 btn btn-lg btn-outline-primary' %>
          </div>
          <div class="col-md-6">
            <%= button_to "Update rate", { controller: :static_pages, action: :update_rate }, method: :get,
                  class: 'w-100 btn btn-lg btn-outline-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card mb-4 rounded-3 shadow-sm">
      <div class="card-header py-3">
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">Dashboard</h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>Transaction statistics</li>
          <li>List of transactions</li>
          <li>Exchange wallet</li>
        </ul>
        <div class="row">
          <div class="col-md-4">
            <%= link_to "Transactions", transactions_path, class: 'w-100 btn btn-lg btn-outline-primary' %>
          </div>
          <div class="col-md-4">
            <%= link_to "Wallets", wallets_path, class: 'w-100 btn btn-lg btn-outline-primary' %>
          </div>
          <div class="col-md-4">
            <%= link_to "Settings", settings_path, class: 'w-100 btn btn-lg btn-outline-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-header text-center">
  Settings that need to be done before using the demo version of the exchanger
  </div>
  <div class="card-body">
    <h5 class="card-title text-center">Add the following options to the settings section:</h5>
    <p class="card-text">Title: "ex_wallet", Value: "bitcoin_address, Description: "Wallet for exchanger"</p>
    <p class="card-text">Title: "ex_fee", Value: "3", Description: "Exchange fee (in %)"</p>
    <p class="card-text">Title: "net_fee", Value: "0.00000600", Description: "Network fee (in BTC)"</p>
    <p class="card-text">Title: "ex_rate", Value: "0.00004046", Description: "Exchange rate (in BTC)". Created automatically the first time the rate is updated</p>
    <h5 class="card-title text-center">In the wallets section:</h5>
    <p class="card-text">Generate or import wallet with Title: "ex_wallet". The address of this wallet will need to be specified in the "ex_wallet" option in the settings section</p>
  </div>
</div>

app/views/transactions/_statistics.html.erb
<div class="table-responsive">
  <table class="table table-bordered table-sm text-center">
  <h3 class="text-center">Transaction statistics</h3>
    <thead>
      <tr>
        <th scope="col">Total success exchange fee</th>
        <th scope="col">Total transactions</th>
        <th scope="col">Total success transactions</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= total_ex_fee(@all_transactions) %></td>
        <td><%= total_tx(@all_transactions) %></td>
        <td><%= total_success_tx(@all_transactions) %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/transactions/_transactions.html.erb
<div class="table-responsive">
  <table class="table table-bordered table-sm">
  <h3 class="text-center">Transactions</h3>
    <thead class="text-center">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Date/Time</th>
        <th scope="col">Recipient email</th>
        <th scope="col">TXid</th>
        <th scope="col">From currency</th>
        <th scope="col">To currency</th>
        <th scope="col">Exchange rate</th>
        <th scope="col">Exchange fee</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      <% transactions.each do |transaction| %>
      <tr>
        <td class="align-middle"><%= link_to transaction.id, transaction_path(transaction) %></td>
        <td class="align-middle"><%= transaction.created_at.strftime("%Y.%m.%d %H:%M:%S") %></td>
        <td class="align-middle"><%= transaction.recip_email %></td>
        <td class="align-middle">
          <div style="word-break: break-all; overflow:auto; max-height:50px">
            <%= link_to transaction.txid, "https://blockstream.info/testnet/search?q=#{transaction.txid}", :target => "_blank" %>
          </div>
        </td>
        <td class="align-middle text-center"><%= transaction.currency_from %></td>
        <td class="align-middle text-center"><%= transaction.currency_to %></td>
        <td class="align-middle"><%= transaction.ex_rate %></td>
        <td class="align-middle"><%= transaction.ex_fee %></td>
        <td class="align-middle text-center"><%= transaction.status %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div class="row">
  <div class="col-md-6">
    <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
  </div>
  <div class="col-md-6 text-end">
    <% if total_tx(all_transactions) > 7 %>
      Per page: <%= link_to_unless_current '7', transactions_path(items: 7) %>
    <% end %>
    <%= link_to_unless_current '20', transactions_path(items: 20) if total_tx(all_transactions) > 20 %>
    <%= link_to_unless_current '30', transactions_path(items: 30) if total_tx(all_transactions) > 30 %>
    <%= link_to_unless_current '40', transactions_path(items: 40) if total_tx(all_transactions) > 40 %>
    <%= link_to_unless_current '50', transactions_path(items: 50) if total_tx(all_transactions) > 50 %>
    <%= link_to_unless_current 'All', transactions_path(items: total_tx(all_transactions)) if total_tx(all_transactions) > 5 %>
  </div>
</div>

app/views/transactions/index.html.erb
<div class="container py-3">
  <%= render 'statistics', transactions: @transactions, all_transactions: @all_transactions %>
  <hr class="my-4">
  <%= render 'transactions', transactions: @transactions, all_transactions: @all_transactions %>
</div>

app/views/transactions/new.html.erb
<div class="container">
<main>
  <div class="py-2 text-center">
    <h3>Exchange form</h3>
  </div>

  <div class="row g-5">
    <div class="col-md-3"></div>
      <div class="col-md-6">
       <%= form_with model: @transaction, data: { controller: "form input-validation", action: "turbo:submit-end->input-validation#validate" } do |form| %>
        <div class="row g-3">
          <div class="col-md-8">
            <%= form.label :amount_send, 'You send', style: "display: block" %>
            <%= form.number_field :amount_send, step: 0.001,
              data: { 'action': 'input->form#updateGetAmount input->form#updateExFeeAmount', 'form-target': 'sendAmount' },
              id: 'send', class: 'form-control', autofocus: true %>
              <p data-input-validation-target="errorContainer" data-error-type="amount_send" class="text-danger" role="alert"></p>
          </div>

          <div class="col-md-4 ">
            <%= form.label :currency_from, 'Currency', style: "display: block" %>
            <%= form.hidden_field :currency_from, value: 'USDT' %>
            <span type="text" class="form-control" id="amount_send">USTD</span>
          </div>

          <div class="card border border-0 my-0">
            <div class="card-body">
              1 USDT ~ <span data-form-target = 'exRate'><%= ex_rate %></span> BTC
            </div>
            <%= form.hidden_field :ex_rate, value: ex_rate %>
          </div>

          <div class="col-md-8 mt-0">
            <%= form.label :amount_get, 'You get', style: "display: block" %>
            <%= form.number_field :amount_get, step: 0.00000001,
              data: { 'action': 'input->form#updateSendAmount input->form#updateExFeeAmount', 'form-target': 'getAmount' },
              id: "get", class: 'form-control' %>
              <p data-input-validation-target="errorContainer" data-error-type="amount_get" class="text-danger" role="alert"></p>
          </div>

          <div class="col-md-4 mt-0">
            <%= form.label :currency_to, 'Currency', style: "display: block" %>
            <%= form.hidden_field :currency_to, value: 'BTC' %>
            <span type="text" class="form-control" id="amount_send">BTC</span>
          </div>

          <div class="col-md-12">
            <%= form.label :recip_email, 'Email', style: "display: block" %>
            <%= form.email_field :recip_email, class: 'form-control' %>
            <p data-input-validation-target="errorContainer" data-error-type="recip_email" class="text-danger" role="alert"></p>
          </div>

          <div class="col-md-12">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                Exchange fee (<span data-form-target = 'exFee'><%= ex_fee %></span>%)
                 - <span data-form-target = 'exFeeAmount'></span>
              </li>
              <li class="list-group-item">Network fee (BTC) - <span data-form-target = 'netFee'><%= net_fee %></span></li>
            </ul>
            <%= form.hidden_field :ex_fee, data: { 'form-target': 'exFeeAmountHidden' } %>
            <%= form.hidden_field :net_fee, value: net_fee %>
          </div>

          <div class="col-md-12">
            <%= form.label :recip_btc_address, 'Wallet address', style: "display: block" %>
            <%= form.text_field :recip_btc_address, class: "form-control" %>
            <p data-input-validation-target="errorContainer" data-error-type="recip_btc_address" class="text-danger" role="alert"></p>
          </div>

          <div class="form-check">
            <%= form.check_box :kyc %> I agree with KYC
            <p data-input-validation-target="errorContainer" data-error-type="kyc" class="text-danger" role="alert"></p>
          </div>

          <div class="row">
            <div class="col-md-6">
              <%= form.submit 'Exchange', class: 'w-100 btn btn-lg btn-outline-primary' %>
            </div>
            <div class="col-md-6">
              <%= link_to "Back", root_path, class: 'w-100 btn btn-lg btn-outline-primary' %>
            </div>
          </div>
        </div>
       <% end %>
      </div>
    <div class="col-md-3"></div>
  </div>
</main>

app/views/transactions/show.html.erb
<div class="container">
<main>
  <div class="py-5 text-center">
    <h3>Exchange <%= @transaction.status %></h3>
  </div>

  <div class="row g-5">
    <div class="col-md-3"></div>
      <div class="col-md-6">
       <form class="needs-validation" novalidate>
        <div class="row g-3">
          <div class="col-sm-8">
            <label for="amount_send" class="form-label">You send</label>
            <span type="text" class="form-control" id="amount_send"><%= @transaction.amount_send %></span>
          </div>

          <div class="col-md-4">
            <label for="currency_from" class="form-label">Currency</label>
            <span type="text" class="form-control" id="currency_from"><%= @transaction.currency_from %></span>
          </div>

          <div class="card border border-0 my-2">
            <div class="card-body">
              1 USDT ~ <%= @transaction.ex_rate %> BTC
            </div>
          </div>

          <div class="col-sm-8 mt-0">
            <label for="amount_get" class="form-label">You get</label>
            <span type="text" class="form-control" id="amount_get"><%= @transaction.amount_get %></span>
          </div>

          <div class="col-md-4 mt-0">
            <label for="currency_to" class="form-label">Currency</label>
            <span type="text" class="form-control" id="currency_to"><%= @transaction.currency_to %></span>
          </div>

          <div class="col-12">
            <label for="recip_btc_adress" class="form-label">Recipient address</label>
            <span type="text" class="form-control" id="recip_btc_adress">
              <%= link_to @transaction.recip_btc_address,
                "https://blockstream.info/testnet/search?q=#{@transaction.recip_btc_address}", :target => "_blank" %>
            </span>
          </div>

          <div class="col-12">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Exchange fee (BTC) - <%= @transaction.ex_fee %></li>
              <li class="list-group-item">Network fee (BTC) - <%= @transaction.net_fee %></li>
            </ul>
          </div>

          <div class="col-12">
            <label for="tx_id" class="form-label">Transaction ID</label>
            <span type="text" class="form-control" id="tx_id">
              <%= link_to @transaction.txid, "https://blockstream.info/testnet/search?q=#{@transaction.txid}", :target => "_blank" %>
            </span>
          </div>

          <hr class="my-4">
          <div class="row">
            <div class="col-md-6">
              <%= link_to "Back", root_path, class: 'w-100 btn btn-lg btn-outline-primary' %>
            </div>
            <div class="col-md-6">
              <%= link_to "New exchange", new_transaction_path, class: 'w-100 btn btn-lg btn-outline-primary' %>
            </div>
          </div>
        </div>
       </form>
      </div>
    <div class="col-md-3"></div>
  </div>
</main>

app/views/wallets/index.html.erb
<div class="container py-3">
  <div class="table-responsive" data-controller='showhide' data-showhide-show-if-value='import'>
    <table class="table table-dark table-bordered text-center table-sm">
      <h3 class="text-center">Add wallet</h3>
      <tbody>
      <tr>
        <%= form_with model: @new_wallet do |f| %>
          <td class="align-middle">
            <%= f.select :action, Wallet.actions, { selected: 'generate' }, {data: {showhide_target: 'input', action: 'change->showhide#toggle'}} %>
          </td>
          <td class="align-middle"><%= f.text_field :title, class: 'form-control', placeholder: 'Title*', autofocus: true %></td>
          <td data-showhide-target='output' class="align-middle">
            <%= f.text_field :key, class: 'form-control', placeholder: 'Key (in base58)*' %>
          </td>
          <td class="align-middle"><%= button_tag type: 'submit', title: "Add", class: "btn btn-primary btn-sm" do %>
              <i class="bi bi-plus-square"></i>
            <% end %>
          </td>
          <% end %>
          <% unless @wallets.size.zero? %>
            <td class="align-middle">
              <%= button_to "Check balance", { controller: :wallets, action: :check_balance },
              method: :get, class: 'btn btn-sm btn-outline-light' %>
            </td>
          <% end %>
          </tr>
        </tbody>
    </table>
  </div>
  <%= render "wallets", wallets: @wallets %>
</div>